/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.revenda.view;

import com.revenda.dao.ClienteDAO;
import com.revenda.dao.VendedorDAO;
import com.revenda.model.Cliente;
import com.revenda.model.Vendedor;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author antonio
 */
public class ListaVendedores extends javax.swing.JPanel {

    VendedorDAO vendedorDAO = new VendedorDAO();
    List<Vendedor> lista;

    /**
     * Creates new form ListaCarros
     */
    public ListaVendedores() {
        try {
            initComponents();
            carregarDadosTabela();
        } catch (SQLException ex) {
            Logger.getLogger(ListaVendedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void carregarDadosTabela() throws SQLException {
        lista = vendedorDAO.listarTodos();
        // Obtém o modelo da tabela
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Remove as linhas existentes na tabela (caso já tenha dados)
        model.setRowCount(0);

        // Preenche a tabela com os dados da lista de clientes
        for (Vendedor vendedor : lista) {
            model.addRow(new Object[]{
                vendedor.getNome(),
                vendedor.getCpf(),
                vendedor.getTelefone(),
                vendedor.getEmail(),
                vendedor.getComissao()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("Novo Vendedor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar Vendedor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir Vendedor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Telefone", "Email", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastraVendedor cadastraVendedor = new CadastraVendedor(null, true, null);
        cadastraVendedor.pack();
        cadastraVendedor.setLocationRelativeTo(this);
        cadastraVendedor.setVisible(true);
        try {
            carregarDadosTabela();
        } catch (SQLException ex) {
            Logger.getLogger(ListaVendedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Você deve escolher um vendedor primeiro!");
        } else {
            Vendedor vendedor = lista.get(jTable1.getSelectedRow());
            CadastraVendedor cadastraVendedor = new CadastraVendedor(null, true, vendedor);
            cadastraVendedor.pack();
            cadastraVendedor.setLocationRelativeTo(this);
            cadastraVendedor.setVisible(true);
            try {
                carregarDadosTabela();
            } catch (SQLException ex) {
                Logger.getLogger(ListaVendedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Você deve escolher um vendedor primeiro!");
        } else {
            if (JOptionPane.showConfirmDialog(this, "Tem certeza dessa exclusão?") == 0) {
                Vendedor vendedor = lista.get(jTable1.getSelectedRow());
                VendedorDAO vendedorDAO = new VendedorDAO();
                try {
                    vendedorDAO.deletar(vendedor.getId_vendedor());
                    carregarDadosTabela();
                } catch (SQLException ex) {
                    Logger.getLogger(ListaVendedores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
